### ISSUE TITLE
Ranchers second edition - station call summary 

### ISSUE THREAD

**Issue by MapReader** [tomwetjens/boardgamefiesta#84]
The table at the end of game summary isn’t showing the calls at any stations other than Kansas City.

**Comment by akwilliamson** [comment]
@MapReader I believe you mean cities, correct?

**Comment by MapReader** [comment]
Yes, the deliveries.  In the table you get at the end of the game, only the deliveries to Kansas City showed - for the other deliveries all the totals were zero for all players.

Kind regards

Ian

**Comment by tomwetjens** [comment]
fixed
