### ISSUE TITLE
Non displayed objective cards

### ISSUE THREAD

**Issue by MapReader** [tomwetjens/boardgamefiesta#86]
In the second edition, objective cards in your discard pile don’t (sometimes or always, I am not sure, but definitely sometimes) show in the player’s “objectives and tiles” screen.

**Comment by MapReader** [comment]
Having watched this through various games, I think the issue is that newly acquired objective cards don’t show up immediately when clicking “objective and rules”, but for some reason take a few turns to appear.

**Comment by tomwetjens** [comment]
Hi @MapReader , thanks for checking.

Currently, objective cards are only shown in the "objectives" dialog when they have been played ("committed") or when you have strategic mode on. 

Normally IRL when you take an objective card it first goes into your discard pile (it is shown in the "discard pile" dialog until the next shuffle) and you don't see it again until you draw it into your hand and you can play it. All played objective cards are layed on the table to be visible for all.
Therefore you would need to remember that you have drawn an objective card that you have not played yet. Strategic mode means that the accounting/remembering that you would do IRL is now done by the system.
