### ISSUE TITLE
Ranchers - 1st (possibly both) edition - game does not end

### ISSUE THREAD

**Issue by MapReader** [tomwetjens/boardgamefiesta#90]
If a player makes their last move to Kansas City, collecting the end game VP chit, but then clicks "leave game" before their (non-) turn comes around again, the game doesn't end - and, it appears, will never end?  

I am guessing that game end is triggered by the next turn start of the player who has already collected the VP chit from the worker market, which then aborts and finishes the game.  But if they've left the table and so their turn never comes around again, the remaining players are condemned to play on for ever....

See https://www.boardgamefiesta.com/gwt/acc30b95-dc4c-4d9c-b1dc-e8900e2cb515

**Comment by tomwetjens** [comment]
@MapReader I rolled back the table to last correct state. Could you please check and you can finish the game if you want
