### ISSUE TITLE
Computer Player Not Responding

### ISSUE THREAD

**Issue by dkelley15** [tomwetjens/boardgamefiesta#96]
The computer player in my 2-player game stopped responding and I'm unable to Force End Turn (message: "Unexpected error from server."). Is this problem more widespread? Is this fixable or just a glitch where I'll need to leave the table? Thanks for any help!

**Comment by tomwetjens** [comment]
Should be fixed now. See 2ae4a92001911ccfb573c85397f91e09165a00ca

**Comment by dkelley15** [comment]
I was able to finish my game. Thanks so much!
