### ISSUE TITLE
Can’t use one out of two exchange tokens (Rancher 2nd edition)

### ISSUE THREAD

**Issue by MapReader** [tomwetjens/boardgamefiesta#99]
If you have two exchange tokens, and you click on the token icon to use one of them, both get used. Even if you click ‘skip’ when he second option to draw two and discard two comes up, you don’t get the second token back.  There seems no way to use one exchange token only, when you have two of them in your hand.

**Comment by tomwetjens** [comment]
Cannot reproduce. If you still experience this, please make a screen recording.
